# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$python $cmd_duration\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol ='[❯](4)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[❯](8)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[fill]
symbol = ' '

[cmd_duration]
format = "[$duration]($style)"

[hostname]
ssh_only = true
format = "@[$ssh_symbol$hostname]($style)"

[username]
show_always = true
format = "[$user]($style)"

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
repo_root_format = " [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncation_symbol = '…/'
home_symbol = ' '
read_only = ' '

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ' '

[python]
format = "[$symbol${pyenv_prefix}(${version} )(($virtualenv) )]($style)"
symbol = ' '
version_format = "v${raw}"
